// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4CdSVcOBhSdfAQmnsMxgbTf_6G2m95Fg',
    appId: '1:683277835308:web:0302ebf24dd7e8df75c589',
    messagingSenderId: '683277835308',
    projectId: 'kathford-5e626',
    authDomain: 'kathford-5e626.firebaseapp.com',
    storageBucket: 'kathford-5e626.appspot.com',
    measurementId: 'G-EEBP9XL5X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWOxPPLo7a9qrkECDgP8C-KcY4MZH3Bg',
    appId: '1:683277835308:android:b854fafd0802d7a375c589',
    messagingSenderId: '683277835308',
    projectId: 'kathford-5e626',
    storageBucket: 'kathford-5e626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXRCyIu4bY_TuTQlhls8EHKfEPrE22xI4',
    appId: '1:683277835308:ios:a0ab7f9aa92911bc75c589',
    messagingSenderId: '683277835308',
    projectId: 'kathford-5e626',
    storageBucket: 'kathford-5e626.appspot.com',
    iosClientId: '683277835308-1n30l25lhgkj24i2fd65busohba8bejp.apps.googleusercontent.com',
    iosBundleId: 'np.com.samirk.kathford',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXRCyIu4bY_TuTQlhls8EHKfEPrE22xI4',
    appId: '1:683277835308:ios:a0ab7f9aa92911bc75c589',
    messagingSenderId: '683277835308',
    projectId: 'kathford-5e626',
    storageBucket: 'kathford-5e626.appspot.com',
    iosClientId: '683277835308-1n30l25lhgkj24i2fd65busohba8bejp.apps.googleusercontent.com',
    iosBundleId: 'np.com.samirk.kathford',
  );
}
